AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  BookmarksToolsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: src/layer
      CompatibleRuntimes:
        - python3.7
      RetentionPolicy: Retain

  BookmarksToolsLayerArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: BookmarksToolsLayerArn
      Type: String
      Value: !Ref BookmarksToolsLayer

  TwitterLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: src/twitter
      CompatibleRuntimes:
        - python3.7
      RetentionPolicy: Retain

  TwitterLayerArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: TwitterLayerArn
      Type: String
      Value: !Ref TwitterLayer

  JinjaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: src/jinja2
      CompatibleRuntimes:
        - python3.7
      RetentionPolicy: Retain

  JinjaLayerArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: JinjaLayerArn
      Type: String
      Value: !Ref JinjaLayer

Outputs:
  BookmarksToolsLayerArn:
    Value: !Ref BookmarksToolsLayer

  TwitterLayerArn:
    Value: !Ref TwitterLayer